targets = [
    { host = "example.com", secure = true, source_path = "/api", dest_path = "/api/v1" },
    { host = "example2.com", secure = true, source_path = "/assets", dest_path = "/static/assets" }
]

cors = true 
port = 4200
